### ISSUE TITLE
RSA two factor authentication causes a login error in the ISE-AddOn

### ISSUE THREAD

**Issue by elcooper** [azureautomation/azure-automation-ise-addon#85] opened 2015-11-17 18:58 UTC
From [UserVoice feedback](https://feedback.azure.com/forums/246290/suggestions/10732185).  

When using the ISE Add-In and logging in with two factor RSA authentication the login page errors out.

Line: 280, Char: 1, Error: Unable to set property ‘onkeypress’ to undefined null reference. Code: 0

**Comment by eamonoreilly** [comment] 2016-01-31 17:41
Closing as I have been unable to reproduce this issue. Will reactivate if it comes up with other users

**Closed as completed by eamonoreilly** 2016-01-31 17:41 UTC
Labels: bug
