### ISSUE TITLE
Error when canceling out of certificate thumbprint dialog

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#78] opened 2015-11-03 22:16 UTC
If you hit the escape key to leave the certificate thumbprint setting, without selecting a certificate, and no certificate is installed, then an error is thrown.

<img width="398" alt="screen shot 2015-11-03 at 2 15 44 pm" src="https://cloud.githubusercontent.com/assets/466713/10923389/7eb262a0-8235-11e5-8372-0dfb7539e78b.png">

![ise add-on azure automation error certificate](https://cloud.githubusercontent.com/assets/466713/10923729/7955333a-8237-11e5-99cd-36600587e0e8.gif)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by eamonoreilly** [comment] 2015-11-12 01:06
Hi Trevor, I'm not able to reproduce this issue. How did you get into a position where there wasn't a certificate thumbprint? 
Thanks,
Eamon

**Comment by pcgeek86** [comment] 2015-11-12 01:57
@eamonoreilly It was a fresh installation of the module on an Azure VM using the Windows 10 RTM image with Visual Studio 2015 Community Edition pre-installed.

Cheers,
Trevor Sullivan

**Comment by eamonoreilly** [comment] 2016-01-23 16:18
Hi Trevor,
I have tried this on Win 10 and other variations and have not been able to repro. I'm going to close this one out but please let me know if you are still able to repro with the latest release and I'll have another look.
Thanks again for helping make the add on better.
Eamon

**Closed as completed by eamonoreilly** 2016-01-23 16:18 UTC

**Comment by pcgeek86** [comment] 2016-01-27 11:55
@eamonoreilly Thanks! Sorry you couldn't repro it. Maybe someone already checked in code that fixed it. :) Either way, glad to know that it isn't an issue anymore! I'll open a new bug if it crops up again.

Ciao,
Trevor Sullivan
