### ISSUE TITLE
"Bad Length" error setting asset value

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#108] opened 2016-04-12 02:31 UTC
I copy / pasted a JSON string into the value of a PSCredential and Variable asset, and I got an error "bad length." I went into the Azure Portal and pasted it with no problem.

**Comment by eamonoreilly** [comment] 2017-12-09 01:37
Cleaning up some issues and I can't reproduce this so closing. Please reopen if it is still an issue.

**Closed as completed by eamonoreilly** 2017-12-09 01:37 UTC
