### ISSUE TITLE
After Update to 0.2.3.6, module cannot be imported anymore

### ISSUE THREAD

**Issue by Stephanevg** [azureautomation/azure-automation-ise-addon#125] opened 2016-09-28 15:04 UTC
Hi,

I just updated to version 0.2.3.6. After restarting the ISE, I keep having the following message:

Import-Module : Could not load file or assembly 
'file://\isa002.domaine.name\UserHomes$\gulicst1\Documents\WindowsPowerShell\Modules\AzureAutomationAuthoringToolkit\0.2.3.6.\ISEAddon\AutomationISE.dll' or one 
of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
- Import-Module AzureAutomationAuthoringToolkit
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
  - FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Since that ".\" in path looked suspisious, I attempted to change line 34 in 'AzureAutomationAuthoringToolkit.psd1' from:
RequiredAssemblies = @(".\ISEAddon\AutomationISE.dll")
To:
RequiredAssemblies = @("ISEAddon\AutomationISE.dll")

but got the same message, with a different path:

Import-Module : Could not load file or assembly 
'file://\isa002.innobit.ch\UserHomes$\gulicst1\Documents\WindowsPowerShell\Modules\AzureAutomationAuthoringToolkit\0.2.3.6\ISEAddon\AutomationISE.dll' or one 
of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
- Import-Module AzureAutomationAuthoringToolkit
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
  - FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by bgelens** [comment] 2016-09-29 10:58
Can't reproduce. Works fine for me. Have a clean install though.
Did you try unblocking the DLL? Exception looks familiar to me and maybe caused by being blocked.

**Comment by stefanstranger** [comment] 2016-09-29 11:00
I also did not have an issue with latest version.

**Comment by Stephanevg** [comment] 2016-09-29 11:44
Thanks for your feeback guys. 
I didn't do much more then clicking the 'update' button in the Configuration panel from the add-on. (Ise was launched as Admin).

To make my environment work again, I simply uninstalled version 0.2.3.6 and re-installed version 0.2.3.5 ; I can now work again.

Did you guys  installed the update from within the ISE?
I'll try a clean install a bit later today (I first need to get some things done ;))

Cheers

**Comment by Stephanevg** [comment] 2016-09-29 11:46
@bgelens I thought so as well, but the dll was already un-blocked. I'll try again a bit later.

**Comment by eamonoreilly** [comment] 2017-01-04 17:21
Closing this issue and can reopen if this shows back up again.

**Closed as completed by eamonoreilly** 2017-01-04 17:21 UTC
